fullnameOverride: fantasy-hockey-stats

api:
  replicaCount: 1

persistence:
  enabled: true
  storageClass: do-block-storage-retain
  accessModes:
    - ReadWriteOnce
  size: 1Gi

imagePullSecrets:
  - name: jonsolakis

seasonImport:
  enabled: true
  seasonIds:
    - "20242025"
    - "20252026"

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: fantasy.jonsolakis.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: fantasy-hockey-stats-tls
      hosts:
        - fantasy.jonsolakis.dev
