deployment:
  replicas: 1

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: jon-hobby-edge
    service.beta.kubernetes.io/do-loadbalancer-type: REGIONAL
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "false"

ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true
  kubernetesCRD:
    enabled: true
  kubernetesGateway:
    enabled: false

ingressRoute:
  dashboard:
    enabled: false

log:
  level: INFO

accessLog:
  enabled: false

metrics:
  addInternals: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
