apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fantasy-hockey-stats-chart
  namespace: fantasy-hockey
spec:
  interval: 10m
  url: https://github.com/jonsolakis/fantasy-hockey-stats.git
  ref:
    commit: 42b144c7a1004bfc4c1c1b048f79a380f9663bcb
