apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:NM0T/v3FHCEr9qdB7I9tmgsTQlHkCk2txcuWFOJMcYICDmK/aeSoy8zHE4+vSVUSBt0D8zgci0nw9I1IpiLn5Fb5ryztJVLykFiAMjVP7l/sPlNJ3UeyYQjT9WeBBT0tck+MjN6OYvyvEcNSPBQ7LWE/MviyjDrdLZMFTlvjyzZU6u7TCdw+zMNu1j2Y0MCAHdB6fNfTW6OC3tFWkBtffeqNmCeNIj3XNGmlcmN/bqwXdawomTYn0lCXET7EMjHc,iv:IBpXjiRn2lkyYNw6xT0uMgRXc/VXvd4SlC1fmGOvT/s=,tag:8A1ixQ6XawzGQdsCkZMXvw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:K+skx7syBgFPBJRm3wr9IjTMqBs=,iv:o+q2g6OikKld+A7nU9Ew9Urkttbg3JgWo5kuzYWoAhk=,tag:B7JlrRhJiOPCeiz03vt3yw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rFyG1JakgvSeMWugSaU6+4X8J6lTcGplIsbsXboBn4atDGvr6HoYaaltdhTHAcK6XdfcDoKb7PNdfyJHGRXusnl1ASIemXXXDMi1hILJCqInS44wAi2Dnw==,iv:31rhoYeoVphLLkM3DCWI8cCUzIt+crrTMpqyzeJRF/4=,tag:lCfJWPU022csdZEaA24e/w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:dSvXFJyBX6TwT4X3IeRsz2uvYag=,iv:LS1OtqSFbkypikWKszIGbpI85TY0xp4xF4XtNPn86DE=,tag:BNZZf8JuJVufehtEL2kcIw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: fantasy-hockey-database
    namespace: fantasy-hockey
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N1QrUTZDcDVXUDdnamI0
            NTBTQW9lZHNLNTZhWE1IdGtVZURpN1dtaFNvCnNzazVETllubWJicWkzUkRpRWRi
            S0Y1dk1lNVZETG9uQng4WDZxN0U0WnMKLS0tIDBlRWp6WVE1U3hVSHRoMFp2eVRC
            ZitzeDI2SzJHc1FOazBxMUdIUk5yYjQKFoyErH5IzikDeYpe+lTo4m97pxh/TTw/
            Goy1ARCJ5Vt7d1FI5iZod3OK+WYEzDOdXFE06anygz5Yl+ZOhj+rLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age129r5376fdv2h00rfe6k8wslcn5n35luhpc7nm00dsg32zc8pwpvsrt2chy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T15:12:10Z"
    mac: ENC[AES256_GCM,data:7U4itOOMR34CS7LKs9miSVChpeAXmOWt8FP/UKCEMWrD5Zpk4frHQyOhyax2G/tjctGdt2wZchdJ3I+MRWF+66KjM93B1TufmUr44u0i1VHZfp2LEj8BlIFgYxcIAJchfgED2afhiGheNvZogFklRt+iOMJJ40aOMpx2WKrUSx4=,iv:gLFgCR50RDwFAalBTTLVGrIDe01+iPU6eM29tAx8c3k=,tag:i+a38TtCyDbRofhxci47jg==,type:str]
    version: 3.13.1
